### ISSUE TITLE
What is MLMD's ROADMAP

### ISSUE THREAD

**Issue by jlewi** [google/ml-metadata#10]
What is the ROADMAP for MLMD?

Would you consider publishing a ROADMAP.md file in the repository?

**Comment by npoly** [comment]
Thanks for the suggestion! We will post a roadmap soon -- we agree this will be useful for the community.

**Comment by jlewi** [comment]
@neuromage @zhitaoli any update on this?

**Comment by npoly** [comment]
Hi Jeremy,

The team is working on a roadmap and will post it soon.

Cheers,

Alkis

**Comment by benmathes** [comment]
(MLMD product manager here)

We presented a public roadmap [here](https://docs.google.com/presentation/d/1OsOR8a8raLxGx2vAdCkuWQGbhz6CuHNv9GgEfx5D9d8/present?slide=id.p). It's not a hyper-technical document, since we think the needs of metadata consumers and producers are fast evolving. The roadmap _is_ directional and helps explain where we are going and why.
