### ISSUE TITLE
Upgrade MLMD grpc to 1.4.0 failed with "Duplicate column name 'byte_value'"

### ISSUE THREAD

**Issue by Bobgy** [google/ml-metadata#135]
MLMD grpc server is stuck in crashloop with error message:

> Check failed: absl::OkStatus() == status (OK vs. INTERNAL: Upgrade query failed: ALTER TABLE `ArtifactProperty` MODIFY COLUMN `string_value` MEDIUMTEXT, ADD COLUMN `byte_value` MEDIUMBLOB; mysql_query failed: errno: Duplicate column name 'byte_value', error: Duplicate column name 'byte_value') MetadataStore cannot be created with the given connection config.

**Comment by Bobgy** [comment]
I verified upgrading an empty MLMD grpc server from 1.0.0 to 1.4.0 completed successfully.
Could this be caused by some kind of race condition?

**Comment by BrianSong** [comment]
Hi Bob,

One of our team member has checked the our schema upgrade queries and there seems to have no potential root cause that related to your error. As you have successfully update the grpc server version, I believe the error should be transient.

Closed the issue for now, and feel free to open it if you encounter any similar/follow-up questions.
