### ISSUE TITLE
Error when MySQL database name contains a dash

### ISSUE THREAD

**Issue by sebastien-prudhomme** [google/ml-metadata#137]
Hi, when using a database name with a dash, the gRPC server throws an error.

I think that there are missing backticks around the database name when creating the database there: https://github.com/google/ml-metadata/blob/839c3501a195d340d2855b6ffdb2c4b0b49862c9/ml_metadata/metadata_store/mysql_metadata_source.cc#L184

And perhaps when using the database there: https://github.com/google/ml-metadata/blob/839c3501a195d340d2855b6ffdb2c4b0b49862c9/ml_metadata/metadata_store/mysql_metadata_source.cc#L194

**Comment by BrianSong** [comment]
Hi sebastien,

The root cause here is not MLMD gRPC server. For the MySQL database name, it may contain alphanumeric characters, underscore and dollar sign. In order to be able to use other ANSI characters, like dash, you should place names in single backquotes. For example, CREATE DATABASE IF NOT EXISTS `database-name-with-dash`.

My advice here would be to not use table names that contain illegal characters (and thus require quoting). They are much more trouble then they are worth it.

Closed the issue for now as this is not MLMD gPRC server error. Please feel free to reopen it if you have any follow-up questions.

**Comment by sebastien-prudhomme** [comment]
Hi @BrianSong, I use a lot of other tools which don't have the problem because they always use backticks when dealing with MySQL database, table or field names.

Even in MLMD there are some line codes with backticks, for instance:
https://github.com/google/ml-metadata/blob/c28a77f0d34cabea675d119bc23a1c2174293b75/ml_metadata/metadata_store/query_config_executor.cc#L617

For me this a limitation in MDMD to not be compatible with all the names a MySQL database can allow.

Will you reject a PR if I submit one?

**Comment by BrianSong** [comment]
I see. Please feel free to submit a PR and we can discuss there.
