### ISSUE TITLE
MLMD comparison with MLFlow/Tracking

### ISSUE THREAD

**Issue by elgalu** [google/ml-metadata#49]
Hi, please forgive my ignorance,

Is this project somehow comparable to MLFlow/Tracking ?
https://mlflow.org/docs/latest/tracking.html#tensorflow-and-keras-experimental

**Comment by benmathes** [comment]
Hey @elgalu,

(for context, I'm a product manager at google working on a few things, including MLMD. Vieww here are mine, not through any official google spokesperson)

Great question! There are some fascinating HCI and product strategy opinions behind the answer.

There are multiple efforts in the ML industry to solve the problem of keeping track of all your ML artifacts: Models, datasets, features, etc. The same way classical software engineering iterated through multiple ways of keeping track of code (central repos like subversion, decentralized repos like git, etc.), ML engineering is evolving the best way to keep track of ML Engineering.

ML-Flow is a model-first view. Contrast to [TFX](https://github.com/tensorflow/tfx)'s  pipeline-first view. Each can be, in theory, recovered from the other. It is easier to recover the model-first view from the pipeline-first view because it only requires hiding information (rest of the pipeline). But a model-first view may not at first store extra information outside the model like its training data, analysis, comparisons with other models trained on the same pipeline, the model's full ineage, etc.

So MLFlow is kinda coming at the problem from a different angle than ML Metadata. Pipeline-first instead of Model-first. We at google have found making the pipeline a first-class citizen more useful.

**Comment by benmathes** [comment]
Some further reading and watching on this from the relevant google teams

https://medium.com/tensorflow/from-research-to-production-with-tfx-pipelines-and-ml-metadata-443a51dac188

https://www.youtube.com/watch?v=drYM04t57tU&feature=youtu.be
