### ISSUE TITLE
ListOptions for additional python client methods

### ISSUE THREAD

**Issue by redramen** [google/ml-metadata#97]
Hey folks, at the moment we're creating some additional contexts to query executions by (i.e. using `get_executions_by_context`) and this works well for our current use case. However as we store more and more executions in mlmd the number of executions we'll pull and filter through locally will increase.

I see that in https://github.com/google/ml-metadata/commit/bf978df6f5e49f6948f4b35089dc6635b4a601ec#diff-c5bcd914b539c92fcfe8120a3db0b0ea297e030035e3591f7ccc5182ab92764e `ListOptions` was added to the `get_executions` method. Is it in the plans to have additional methods e.g. `get_executions_by_context` be updated to take in `ListOptions` as well? That would help our use case out.

**Comment by hughmiao** [comment]
@redramen , the `get_executions_by_context` used list options in the grpc side in recent [commit](https://github.com/google/ml-metadata/commit/15ed9f7ba4813e371f6f2d5dc964e22adb8439e1) , and released in 0.25.1+, this address the tfx issue which requires the users to explicitly setting max grpc return size. At this point, we do not have plans to surface the list options to the `get_executions_by_context` py client yet. 

Instead, we plan to extend list options and add declarative filter, so that `get_executions` can filter neighbor contexts and properties, and it allows to deprecate other template methods gradually (e.g., get_artifacts_by_uri, get_artifacts_by_type, etc).
